name: first workflow 
on:workflow_dispatch
jobs:
  first-job:
    runs-on:ubuntu-latest
    steps:
      -name:print greeting
      run:echo "hello weorld"
      -name:print good bye
      run:echo "good bye world"
  
